### ISSUE TITLE
No design-time support

### ISSUE THREAD

**Issue by lordofscripts** [Jonathan435/Business-Clocks-Charts#2]
Since it is not very productive to work blindly as in the demo app, I was hoping to drop either of the 3 controls onto my windows forms and from there modify the properties, rather than creating it at runtime and having to guess where it should be placed, etc.

I tried to put the DLL into the Toolbox but VS.2017 says there are no components there that can be placed on the toolbox.

**Comment by Jonathan435** [comment]
Correct, there is no design-time support, if this library will be more popular among community developers i will add design-time support, also, you are more than welcome to take part in the project.
BTW-visual studio is the best IDE ever but it made us (Microsoft developers) very spoiled with this perfect drag and drop interface, for now the old fashion way is required (-:
