### ISSUE TITLE
No API documentation

### ISSUE THREAD

**Issue by lordofscripts** [Jonathan435/Business-Clocks-Charts#3]
There is no documentation that indicates which properties can be used to accomplish a certain look. If you want people to use the library you should consider their time is also precious, they want to get it working ASAP and then if needed delve into the code.

**Comment by lordofscripts** [comment]
For example, among others there is a reference to some timer in the public properties, but how is that supposed to be used? That is just one example.

**Comment by Jonathan435** [comment]
Documentation will be added to the repository. its under construction in the ReadMe.md file and will be ready soon.

**Comment by Jonathan435** [comment]
Documentation added to the repository, I will be happy for your opinion the documentation is sufficient.
Also XML documentation was added to the library code.
