### ISSUE TITLE
Bug in property set, does not autoupdate

### ISSUE THREAD

**Issue by lordofscripts** [Jonathan435/Business-Clocks-Charts#8]
I suppose that happens because you use a panel inside of your control. When one sets a property like the cut line color for example, it is not updated in the visual until the user calls RefreshClock(). You should take care of that automatically in the setter property (as per good design practices).

**Comment by Jonathan435** [comment]
thank you for the 8 open issues, i will notify as soon as possible on every bug fix.
regards,
Jonathan.

**Comment by Jonathan435** [comment]
This issue has been treated, now all properties refresh the clock inside the setter. new version with the rest of the requests will be uploaded this weekend.
